server:
  port: 8081
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath(可以去除D:项目在哪个盘符就存在哪)，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-file-size: 50MB #设置单个文件最大长度
      max-request-size: 50MB #最大请求文件的大小
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.210.77:3312/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: cpc!23#@
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  main:
    allow-bean-definition-overriding: true

leetcode:
  sms:
    url: http://106.ihuyi.com/webservice/sms.php?method=Submit
    account: C80305290
    password: e6e474c1e7b4f88889f3fd67b474bd68
upload:
  dir: D:\\download

tess4j:
  datapath: D:\develop\Tesseract-OCR\tessdata

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #自定义类型处理器包路径
  type-handlers-package: top.arhi.mp.handler

ip2region:
  external: false
  index-block-size: 4096
  total-header-size: 8192
  location: classpath*:ip2region/ip2region.xdb

amap:
  key: 659f057c4e1b3c72ae58027363b3afb9



