server:
  port: 8081
spring:
  servlet:
    multipart:
      #开启文件上传
      enabled: true
      #限制文件上传大小为50M
      max-file-size: 50MB
fdfs:
  http:
    secret_key: FastDFS1234567890
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 114.132.210.77:22122
  web-server-url: http://114.132.210.77:8888/
# fastDFS
# fdfs.so-timeout=1501
# fdfs.connect-timeout=601
# fdfs.thumb-image.width=150
# fdfs.thumb-image.height=150
# fdfs.web-server-url=你的IP/
# fdfs.tracker-list[0]=你的IP:22122
# fdfs.http.anti_steal_token = true
# fdfs.http.secret_key = FastDFS1234567890
