spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6380
    password: root
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
rocketmq:
  name-server: 127.0.0.1:9876 #服务器ip
  producer:
    group: sanyouProducer
