spring:
  redis:
    host: 114.132.210.77
    port: 6380
    password: cpc!23#@
    database: 0
    # 连接池配置
    jedis:
      pool:
        max-active: 20      #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        #连接池中的最大空闲连接
        min-idle: 0         #连接池中的最小空闲连接
        timeout: 1000      #连接超时时间（毫秒）。我设置的是1秒
  rabbitmq:
    host: 114.132.210.77
    port: 5672
    virtual-host: /
    username: admin
    password: hjm029796
  activemq:
    broker-url: tcp://114.132.210.77:61616
    user: admin
    password: admin
    close-timeout: 15s
rocketmq:
  name-server: 114.132.210.77:9876 #服务器ip
  producer:
    group: sanyouProducer