spring:
  redis:
    host: 114.132.210.77
    port: 6380
    password: cpc!23#@
  rabbitmq:
    host: 114.132.210.77
    port: 5672
    virtual-host: /
    username: admin
    password: hjm029796
rocketmq:
  name-server: 114.132.210.77:9876 #服务器ip
  producer:
    group: sanyouProducer