server:
  port: 8763
spring:
  application:
    name: eureka-server-ha
eureka:
  instance:
    hostname: eureka-server-2 # 主机名
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka,http://eureka-server-1:8762/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
    register-with-eureka: true # 是否将自己的路径 注册到eureka上。eureka server 不需要的，eureka provider client 需要
    fetch-registry: true # 是否需要从eureka中抓取路径。eureka server 不需要的，eureka consumer client 需要
  server:
    enable-self-preservation: false # 关闭自我保护机制
    eviction-interval-timer-in-ms: 3000 # 检查服务的时间间隔
