spring:
  application:
    name: springboot-mongodb
  data:
    mongodb:
      authentication-database: admin
      database: tanhua
      host: 114.132.210.77
      password: l3SCjl0HvmSkTtiSbN0Swv40spYnHhDV
      port: 27018
      username: tanhua
